.replace("CREATE_INSTANT_INVITE","Anında Davet Bağlantısı Oluşturma")
.replace("MANAGE_CHANNELS","Kanalı Yönetme")
.replace("ADD_REACTIONS","Tepki Ekleme")
.replace("SEND_MESSAGES","Mesaj Gönderme")
.replace("SEND_TTS_MESSAGES","TTS Mesajı Gönderme")
.replace("EMBED_LINKS","Embed Linkler")
.replace("ATTACH_FILES","Dosya Paylaşımı")
.replace("READ_MESSAGE_HISTORY","Mesaj Geçmişini Okuma")
.replace("MENTION_EVERYONE","Herkesi Etiketleyebilme")
.replace("USE_EXTERNAL_EMOIS","Harici Emoji Kullanımı")
.replace("MANAGE_ROLES","Rolleri Yönetme")
.replace("MANAGE_WEBHOOKS","Webhook'ları Yönetme")
.replace("PRIORITY_SPEAKER","Öncelikli Konuşmacı")
.replace("STREAM","Yayın Yapma")
.replace("VIEW_CHANNEL","Kanalı Görüntüleme")
.replace("CONNECT","Bağlanma")
.replace("SPEAK","Konuşma")
.replace("MUTE_MEMBERS","Üyeleri Susturma")
.replace("DEAFEN_MEMBERS","Üyeleri Sağırlaştırma")
.replace("MOVE_MEMBERS","Üyeleri Taşıma")
.replace("USE_VAD","Ses Algılama ile Konuşma")